# Generated by Django 4.2.13 on 2024-06-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_remove_message_file_remove_message_read_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image')], default='text', max_length=5),
        ),
    ]
