# Generated by Django 4.2.13 on 2024-06-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_alter_message_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='last_message_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversation',
            name='user1_unread_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conversation',
            name='user2_unread_count',
            field=models.IntegerField(default=0),
        ),
    ]
