# Generated by Django 4.2.13 on 2024-06-26 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_message_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='last_message_sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_message_sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
